//
//  PlantSpecies.swift
//  ToDoGame
//
//  Created by Дарья Селезнёва on 30.07.2021.
//

import Foundation

struct PlantSpecies {
    var id: Int
    var title: String
    var description: String
    var buyCostGold: Int
    var buyCostDonation: Int
    var sellCost: Int
    var type: PlantType
    var waterConsumption: Int
    var fertilizerConsumption: Int
    var fertilizerOutput: Int?
    var firewoodOutput: Int?
    var levelRequired: Int
    var daysTilBlooming: Int
    var daysTilHarvest: Int
    var nominalYield: Int
    var fruitingDuration: Int
    
    static let plants: [PlantSpecies] = [
        PlantSpecies(id: 1,
                     title: Strings.tomato,
                     description: "",
                     buyCostGold: 3,
                     buyCostDonation: 0,
                     sellCost: 1,
                     type: .bush,
                     waterConsumption: 2,
                     fertilizerConsumption: 2,
                     fertilizerOutput: 2,
                     levelRequired: 1,
                     daysTilBlooming: 10,
                     daysTilHarvest: 12,
                     nominalYield: 3,
                     fruitingDuration: 7),
        PlantSpecies(id: 2,
                     title: Strings.strawberry,
                     description: "",
                     buyCostGold: 4,
                     buyCostDonation: 0,
                     sellCost: 1,
                     type: .bush,
                     waterConsumption: 1,
                     fertilizerConsumption: 1,
                     fertilizerOutput: 1,
                     levelRequired: 2,
                     daysTilBlooming: 6,
                     daysTilHarvest: 8,
                     nominalYield: 2,
                     fruitingDuration: 7),
        PlantSpecies(id: 3,
                     title: Strings.apple,
                     description: "",
                     buyCostGold: 5,
                     buyCostDonation: 1,
                     sellCost: 1,
                     type: .tree,
                     waterConsumption: 3,
                     fertilizerConsumption: 3,
                     firewoodOutput: 20,
                     levelRequired: 3,
                     daysTilBlooming: 36,
                     daysTilHarvest: 40,
                     nominalYield: 10,
                     fruitingDuration: 10),
        PlantSpecies(id: 4,
                     title: Strings.sunflower,
                     description: "",
                     buyCostGold: 3,
                     buyCostDonation: 1,
                     sellCost: 1,
                     type: .bush,
                     waterConsumption: 2,
                     fertilizerConsumption: 2,
                     fertilizerOutput: 2,
                     levelRequired: 4,
                     daysTilBlooming: 14,
                     daysTilHarvest: 16,
                     nominalYield: 60,
                     fruitingDuration: 1),
        PlantSpecies(id: 5,
                     title: Strings.walnut,
                     description: "",
                     buyCostGold: 6,
                     buyCostDonation: 1,
                     sellCost: 1,
                     type: .tree,
                     waterConsumption: 4,
                     fertilizerConsumption: 4,
                     firewoodOutput: 24,
                     levelRequired: 5,
                     daysTilBlooming: 40,
                     daysTilHarvest: 45,
                     nominalYield: 7,
                     fruitingDuration: 24),
        PlantSpecies(id: 6,
                     title: Strings.watermelon,
                     description: "",
                     buyCostGold: 6,
                     buyCostDonation: 1,
                     sellCost: 1,
                     type: .bush,
                     waterConsumption: 3,
                     fertilizerConsumption: 3,
                     fertilizerOutput: 2,
                     levelRequired: 6,
                     daysTilBlooming: 16,
                     daysTilHarvest: 18,
                     nominalYield: 1,
                     fruitingDuration: 3),
        PlantSpecies(id: 7,
                     title: Strings.cherry,
                     description: "",
                     buyCostGold: 6,
                     buyCostDonation: 1,
                     sellCost: 1,
                     type: .tree,
                     waterConsumption: 4,
                     fertilizerConsumption: 4,
                     firewoodOutput: 18,
                     levelRequired: 7,
                     daysTilBlooming: 30,
                     daysTilHarvest: 34,
                     nominalYield: 24,
                     fruitingDuration: 7),
        PlantSpecies(id: 8,
                     title: Strings.pineapple,
                     description: "",
                     buyCostGold: 7,
                     buyCostDonation: 1,
                     sellCost: 1,
                     type: .bush,
                     waterConsumption: 2,
                     fertilizerConsumption: 2,
                     fertilizerOutput: 2,
                     levelRequired: 8,
                     daysTilBlooming: 14,
                     daysTilHarvest: 17,
                     nominalYield: 1,
                     fruitingDuration: 4),
        PlantSpecies(id: 9,
                     title: Strings.avocado,
                     description: "",
                     buyCostGold: 8,
                     buyCostDonation: 1,
                     sellCost: 2,
                     type: .tree,
                     waterConsumption: 4,
                     fertilizerConsumption: 4,
                     firewoodOutput: 22,
                     levelRequired: 8,
                     daysTilBlooming: 37,
                     daysTilHarvest: 42,
                     nominalYield: 6,
                     fruitingDuration: 9),
        PlantSpecies(id: 10,
                     title: Strings.coconut,
                     description: "",
                     buyCostGold: 8,
                     buyCostDonation: 2,
                     sellCost: 2,
                     type: .tree,
                     waterConsumption: 5,
                     fertilizerConsumption: 5,
                     firewoodOutput: 26,
                     levelRequired: 9,
                     daysTilBlooming: 42,
                     daysTilHarvest: 46,
                     nominalYield: 7,
                     fruitingDuration: 8),
        PlantSpecies(id: 11,
                     title: Strings.chiliPepper,
                     description: "",
                     buyCostGold: 7,
                     buyCostDonation: 2,
                     sellCost: 1,
                     type: .bush,
                     waterConsumption: 2,
                     fertilizerConsumption: 2,
                     fertilizerOutput: 2,
                     levelRequired: 9,
                     daysTilBlooming: 14,
                     daysTilHarvest: 17,
                     nominalYield: 3,
                     fruitingDuration: 5),
        PlantSpecies(id: 12,
                     title: Strings.dragonfruit,
                     description: "",
                     buyCostGold: 10,
                     buyCostDonation: 2,
                     sellCost: 2,
                     type: .bush,
                     waterConsumption: 3,
                     fertilizerConsumption: 3,
                     fertilizerOutput: 3,
                     levelRequired: 10,
                     daysTilBlooming: 20,
                     daysTilHarvest: 22,
                     nominalYield: 4,
                     fruitingDuration: 6)
    ]
}

enum PlantType: Int {
    case bush
    case tree
}

extension PlantSpecies: ShopItem {}
